Fix compilation error due to low SDK version
Fixes this error: Your project is configured to compile against Android SDK 34, but the following plugin(s) require to be compiled against a higher Android SDK version:
- flutter_plugin_android_lifecycle compiles against Android SDK 35
- image_picker_android compiles against Android SDK 35
- integration_test compiles against Android SDK 35
- local_auth_android compiles against Android SDK 35
- path_provider_android compiles against Android SDK 35
- shared_preferences_android compiles against Android SDK 35
- url_launcher_android compiles against Android SDK 35
- webview_flutter_android compiles against Android SDK 35